language: python
dist: xenial
matrix:
  include:
    - python: 3.7
      env: TOXENV=check
    - python: 3.7
      env: TOXENV=py37  
    - python: 3.8
      env: TOXENV=py38-coverage
    - python: 3.8
      env: TOXENV=py38  
    - python: 3.8
      env: TOXENV=docs
install:
  - pip install tox
  - pip install codecov
script:
  tox -e $TOXENV
after_success:
  - codecov 
